### ISSUE TITLE
[TASK] Address "switch" should support switching to a different wallet

### ISSUE THREAD

**Issue by drewstone** [tangle-network/dapp#2231]
# Overview
Currently the "switch" functionality when clicking the wallet button only allows you to switch your metamask address or your polkadotJS address. The flow for switching wallets entirely requires first disconnecting and then connecting a different wallet. This flow could be wrapped up together from "switch" as well, no?

**Comment by AtelyPham** [comment]
I believe we should maintain the current functionality of switching accounts but rename it to `switch account` instead of just `switch` to reduce confusion. Additionally, we can add another button for switching to another wallet in the dropdown menu.

**Comment by yurixander** [comment]
Yes, I think it makes sense to keep the current functionality, BUT improve the UI to make it more smooth/easy to use.
