### ISSUE TITLE
[TASK] Update All Networks/Assets/Identity Selection Modals

### ISSUE THREAD

**Issue by drewstone** [tangle-network/dapp#2475]

**Comment by monaiuu** [comment]
## Description
Improve the visual presentation of all selection modals for networks, assets, and identities by adjusting the layout and dimensions.

### Items:
- **Selection Menu List:** Adjust the selection menu list to fill the full width of the modal; remove any existing margins to ensure the list spans the entire width.
- **Update Modal Dimensions:** Update the height and width of the selection modals to improve visual presentation and usability. Ensure the new dimensions are consistent across all selection modals for networks, assets, and identities.

### Screenshot

### Figma Link
