### ISSUE TITLE
[TASK] GraphQL server that records participation metrics every hour

### ISSUE THREAD

**Issue by drewstone** [tangle-network/dapp#2567]
# Overview
We want to be tracking participation metrics on an hourly basis (or daily, etc. time intervals). This will allow us to build graphics that show how the growth is going for marketing purposes and GTM purposes.

Things we need to be tracking on mainnet soon:
- Restaking deposits for all assets
- Liquid staking deposits for all assets
- Delegating any asset to an operator
- Having completed entire flows.
- Bridged assets over Hyperlane
- Bridge assets over Chainport
- Registered operator
- Registered operator in a blueprint
- Developed a blueprint
- Deployed a blueprint

CC @1xstj what other interactions am I missing here?

**Comment by ThugOG** [comment]
Transaction Metrics:
Total number of transactions per time interval.
Average transaction value.

 Incentive Programs:
Participation in any incentive or reward programs.
Total rewards distributed.

**Comment by AtelyPham** [comment]
Progress is being tracked in this checklist: https://github.com/webb-tools/webb-graphql/issues/183.
