### ISSUE TITLE
[FEAT] Add onboarding modals for restaking & bridge pages

### ISSUE THREAD

**Issue by yurixander** [tangle-network/dapp#2577]
Write up onboarding items for the restaking & bridge pages to help first time users quickly understand what the purpose and usage of the page is. It should be succinct but useful.

- [x] Implement onboarding modal logic and the ability to remember when it was previously seen
- [x] Add a help (?) button on the top right to allow users to re-open the onboarding modal in case they forget how to use the page.
- [x] Help button is hidden on pages that don't have onboarding defined
- [x] Add onboarding items for the **nomination page**
- [x] Add onboarding items for the **bridge page**
- [x] Add onboarding items for the **liquid staking page** (added on #2570)
- [x] Add onboarding items for the **restaking page**

**Comment by AtelyPham** [comment]
We should add a checkbox for "not showing this modal in the future" and save this preference in local storage to enhance the user experience, as it can be frustrating for users if the modal reappears every time the page is refreshed.

**Comment by yurixander** [comment]
> We should add a checkbox for "not showing this modal in the future" and save this preference in local storage to enhance the user experience, as it can be frustrating for users if the modal reappears every time the page is refreshed.

@AtelyPham Yes, the modal is automatically hidden after the first page visit. The state is saved to local storage. The user can use the help button at the top right of the page to re-open the modal.
