### ISSUE TITLE
[CHECKLIST] Liquid Staking & Restaking Issue Tracker

### ISSUE THREAD

**Issue by devpavan04** [tangle-network/dapp#2611]
- [x] #2612
- [x] #2613 
- [x] #2614 
- [x] #2615 
- [x] #2616 
- [x] #2617 
- [x] #2620 
- [x] #2621 
- [x] #2624
- [x] #2625 
- [x] #2626 
- [x] Disable `Create Pool` button if there's no account connected

**Comment by drewstone** [comment]
Mint Liquid Staking Tokens (LSTs) to earn & restake on Tangle Mainnet.
