### ISSUE TITLE
[TASK] Create a Pool list component

### ISSUE THREAD

**Issue by devpavan04** [tangle-network/dapp#2615]
### Overview

When we click on the `select a pool` button, nothing happens ⚠️ bug. We should create a pool list modal, similar to the token/chain/operator list component, and use it.

https://github.com/user-attachments/assets/2f756a28-b667-4e37-873b-b4c8080cdb7a

**Comment by yurixander** [comment]
This one's supposed to be sort of a message that tells you you need to select a pool below on the table 👀 I guess it does seem like a button that would trigger an action...

@devpavan04 Any suggestions on how to make it clearer? For now, closing as not planned

**Comment by yurixander** [comment]
We went with an alternative approach to that of using modals, mostly because there's more info to show so a table would make sense. For example, there's APY, validators, etc. so showing all that on a modal might be a bit unnatural @devpavan04
