### ISSUE TITLE
[TASK] Display Unstaked Balance in Pools Table During Unstaking Period

### ISSUE THREAD

**Issue by devpavan04** [tangle-network/dapp#2625]
### Overview

After a user clicks the `Schedule Unstake` button and successfully unstakes, there is no clear way to see the amount currently being unstaked. We should add a column in the pools table that displays the unstaked balance by the user for each pool until it is fully withdrawn and appears in their wallet. Currently, only the total pool stake is adjusted, leaving users unable to track their specific unstaked amount during the unstaking period or prior to withdrawal.

https://github.com/user-attachments/assets/8d12812f-e574-4f7a-98e0-1f27d0ce4ed3

**Comment by yurixander** [comment]
This will be addressed in #2623
