### ISSUE TITLE
[TASK] Maintain Table Dropdown State When Switching Between Tables

### ISSUE THREAD

**Issue by devpavan04** [tangle-network/dapp#2626]
### Overview

Most user interactions occur within an opened pools dropdown of a network, which users frequently access. Currently, switching between tabs forces users to reopen the dropdown each time, creating unnecessary friction. To improve usability, consider keeping the dropdown open by default, especially in the current setup where only one network is available.

- [x] Automatically expand the first row of the tables

https://github.com/user-attachments/assets/1268a62a-f37c-4bfb-8c08-49b3714d018b

**Comment by yurixander** [comment]
> I think we also need smoother transitions here, thoughts?

@drewstone I could add a fade out/in transition when switching tabs to make it smoother?
