### ISSUE TITLE
[BUG] Navigation bar link leads to 404 

### ISSUE THREAD

**Issue by ThugOG** [tangle-network/dapp#2631]
When navigating to the Tangle Tools website and selecting the "Developer" option from the navigation bar, the link leads to a 404 error page, indicating that the page for the developer section does not exist or is not properly configured.

***Steps to Reproduce:***
Open the web browser and go to www.tangle.tools.
Locate the navigation bar at the top of the page.
Click on the "Developers" link in the navigation menu.
The browser will redirect to a page that displays a "404 - Page Not Found" error.

***Expected Behavior:***
The "Developers" link should either:
Direct to a page containing developer resources, documentation, or relevant information.
If the link is meant to be inactive, it should not be visible or should be clearly marked as under construction or coming soon.

***Actual Behavior:***
Instead of leading to a development page or resources, it results in a 404 error page.

**Comment by yurixander** [comment]
CC @monaiuu 👀

**Comment by monaiuu** [comment]
@ThugOG thanks for reporting, link is updated!
