### ISSUE TITLE
[UI] Improve Dark Mode Readability and Contrast

### ISSUE THREAD

**Issue by AtelyPham** [tangle-network/dapp#2659]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your UI update related to a problem? Please describe.

We've received feedback regarding the difficulty reading content in our app's dark mode due to harsh contrast and dark-on-dark components. We need to address these concerns to improve overall user experience and accessibility.

Current Issues:
1. White font on dark background creates excessive contrast, causing eye strain.
2. Some components are dark-on-dark, making them hard to distinguish.
3. Overall readability in dark mode is poor, especially in low-light conditions.

### Describe the solution you'd like (include image or link to prototype)

1. Replace white font in dark mode with softer colors
2. Review and adjust the color scheme of dark-on-dark components to improve visibility.
3. Consider removing or reducing transparency in certain UI elements to enhance readability.
4. Evaluate the current grey fonts and determine if they need further adjustment.

Goals:
- Improve overall readability in dark mode
- Reduce eye strain for users in low-light environments
- Maintain a cohesive and attractive design while prioritizing usability

**Comment by yurixander** [comment]
Do you think this task has been addressed in the recent design jam changes, or it still needs revision? @AtelyPham

**Comment by AtelyPham** [comment]
We can close this @yurixander.
