### ISSUE TITLE
[TASK] Get rid of the `icons` library

### ISSUE THREAD

**Issue by yurixander** [tangle-network/dapp#2683]
Consider getting rid of the icons library, where we have manually created an icon per file, with the SVG path inside. Instead of this, we could use pre-existing and popular libraries, such as React icons or as Drew suggested: heroicons along with web3icons.

- [ ] Determine whether it is a good idea to get rid of the icons library, and whether it is too time consuming to refactor the codebase where icons are already used
- [ ] Introduce the new libraries, and start to gradually change icons one by one throughout the projects
- [ ] Remove the icons library

**Comment by drewstone** [comment]
We might keep this and avoid the headache.

**Comment by yurixander** [comment]
> We might keep this and avoid the headache.

Agreed, can save time on this and redirect towards something else.
